#  https://github.com/paramsinghvc/Timely/blob/main/.github/workflows
name: Pull Request into Master, Develop and Preprod
description: 'Checks out code, caches node_modules, installs dependencies'

on:
  workflow_call:  
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'
  pull_request:
    # The workflow gets triggered when there's pull request against these branches are raised
    branches:
      - "main"
      - "develop"
      - "preprod"
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  #First job: Install dependencies if no cache hit
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Directory
        run: pwd

      - name: Check development environment
        run: node -v && npm -v && java -version

      - name: Install Node modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Linting
        run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Tests
        run: npm run test -- --json --outputFile=jest-results.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Jest Tests
          path: jest-results.json
          reporter: jest-json

      # - name: Unit & Integration tests
      #   run: yarn test:ci

      # - name: Jest coverage report
      #   uses: ArtiomTr/jest-coverage-report-action@v2.0.6
      #   with:
      #     coverage-file: ./jest-report.json
      #     base-coverage-file: ./jest-report.json